### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by jaroslavas** [icerockdev/moko-template#11]
Xcode 11.3.1, cocoapods 1.9.3. Xcode commandline tools are installed.
When running `pod install` I get an error:

```
prepare MultiPlatformLibrary.framework (require some time...)
e: org.jetbrains.kotlin.konan.MissingXcodeException: An error occurred during an xcrun execution. Make sure that Xcode and its command line tools are properly installed.
        at org.jetbrains.kotlin.konan.target.CurrentXcode.xcrun(Xcode.kt:77)
...
Caused by: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /usr/bin/xcrun command returned non-zero exit code: 72.
output: 
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:105)
...
e: org.jetbrains.kotlin.konan.MissingXcodeException: An error occurred during an xcrun execution. Make sure that Xcode and its command line tools are properly installed.
        at org.jetbrains.kotlin.konan.target.CurrentXcode.xcrun(Xcode.kt:77)
...
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mpp-library:feature:config:compileKotlinIosX64'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mpp-library:feature:list:compileKotlinIosX64'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mpp-library:domain:compileKotlinIosX64'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

```

Is there anything that should be done differently?
Android projects build and runs fine (but only from Android studio v 4.0.1, not from Idea CE).

**Comment by Dorofeev** [comment]
Please check that Command line tools is selected in
> Xcode > Preferences > Locations

**Comment by jaroslavas** [comment]
After upgrading from Mojave to newest Catalina, everything magically started working.
PS. Thanks a lot for opensourcing your libraries!
