### ISSUE TITLE
xcode 10.1 support

### ISSUE THREAD

**Issue by winnerawan** [icerockdev/moko-template#15]
Is this only work in macos catalina with xcode 11+ only? or maybe someday i can use xcode 10?
i use macos high sierra and xcode 10.1 got this exception when running `pod install`

````bash
Analyzing dependencies
Downloading dependencies
prepare MultiPlatformLibrary.framework (require some time...)
e: java.lang.IllegalStateException: Unsupported Xcode version 10.1, minimal supported version is 11.0.
        at org.jetbrains.kotlin.konan.target.AppleConfigurablesImpl.checkXcodeVersion(Apple.kt:94)
        at org.jetbrains.kotlin.konan.target.AppleConfigurablesImpl.access$checkXcodeVersion(Apple.kt:24)
        at org.jetbrains.kotlin.konan.target.AppleConfigurablesImpl$xcodePartsProvider$2.invoke(Apple.kt:72)
        at org.jetbrains.kotlin.konan.target.AppleConfigurablesImpl$xcodePartsProvider$2.invoke(Apple.kt:24)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)

**Comment by Alex009** [comment]
@winnerawan this limits from https://github.com/JetBrains/kotlin-native
i think no plans about support old xcode

**Comment by winnerawan** [comment]
@Alex009 Ok, thanks for fast reply. Will try to upgrade this night.
